server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5